export interface PrinterObjectNotification {
    /**
     * The eventtime is a timestamp generated by Klipper
     * when the update was originally pushed.
     * This timestamp is a float value, relative to
     * Klipper's monotonic clock.
     */
    eventTime: number;
    /**
     * The data from the object notification in the format.
     * {
     *   "objectType": notificationData
     * }.
     * Refer to https://moonraker.readthedocs.io/en/latest/printer_objects/
     * for the schema of the notificationData depending on the object type.
     */
    objectNotification: unknown;
}